version: "3.8"
services:
  app:
    build:
      args:
        user: server
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: looperbattle
    container_name: looperbattle-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 6001:6001
    volumes:
      - ./:/var/www
    networks:
      - looperbattle
    user: root

  nginx:
    image: nginx:alpine
    container_name: looperbattle-nginx
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - looperbattle

  postgres:
    image: postgres:14.2
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - looperbattle

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: looper@looper.com
      PGADMIN_DEFAULT_PASSWORD: l00p3r2023
      PGADMIN_LISTEN_PORT: 80
    networks:
      - looperbattle
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  looperbattle:
    driver: bridge
